using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace problem2
{
	/// <summary>
	/// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	/// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	/// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	/// </summary>
	class Program
	{
		static void Main(string[] args)
		{
			Console.WriteLine(Fibonacci(4000000).Where(n => n % 2 == 0).Sum());
			Console.ReadLine();
		}

		static IEnumerable<int> Fibonacci(int end)
		{
			int a = 0;
			int b = 1;
			while (a + b < end)
			{
				int next = a + b;
				a = b;
				b = next;
				yield return b;
			}
		}
	}
}
